from . import hostel
from . import hostel_book
from . import hostel_room
from . import hostel_student
from . import hostel_amenities
from . import hostel_categ
from . import res_config_settings
from . import sample_auth_http
from . import ir_action_act_window
from . import ir_ui_view
from . import base
